set( ENV{CAMERA_SUITE_SRC_PATH} /usr/src/framos/camerasuite )
set( ENV{CAMERA_SUITE_LIB_PATH} /usr/lib/framos/camerasuite )
set( ENV{CAMERA_SUITE_INCLUDE_PATH} /usr/include/framos/camerasuite )
set( ENV{CAMERA_SUITE_DOC_PATH} /usr/doc/framos/camerasuite )
set( ENV{CAMERA_SUITE_PATH} /usr/src/framos/camerasuite )
set( ENV{CAMERA_SUITE_PACKAGE} /usr/src/framos/camerasuite/CMakePackages )
set( ENV{CAMERA_SUITE_TOOLCHAIN_PATH} /usr/src/framos/camerasuite/Toolchain )
set( ENV{CAMERA_SUITE_GENICAM_ROOT_V3_0} /usr/src/framos/camerasuite/GenICam )
set( ENV{CAMERA_SUITE_GENICAM_LOG_CONFIG_V3_0} /usr/src/framos/camerasuite/GenICam/log/config-unix/DefaultLogging.properties )
set( ENV{CAMERA_SUITE_GENICAM_CACHE_V3_0} $HOME/.cache/genicam )
set( ENV{CAMERA_SUITE_CUSTOM_PATH} $HOME/.local/custom )

macro(add_camerasuite)
	string (REPLACE "\\" "/" CAMERA_SUITE_MODULE_PATH "$ENV{CAMERA_SUITE_PACKAGE}")
    list (APPEND CMAKE_MODULE_PATH "${CAMERA_SUITE_MODULE_PATH}" /usr/src/framos/camerasuite/CMakePackages)
    find_package(CameraSuite REQUIRED)
    include_directories(${CAMERASUITE_INCLUDE_DIRS})
    target_sources(${ARGV0} PRIVATE "${CAMERASUITE_INCLUDE_DIRS}/smcs_cpp/CameraSDK.cpp")
    target_include_directories(${ARGV0} PRIVATE ${CAMERASUITE_INCLUDE_DIRS})
    target_link_libraries(${ARGV0} PUBLIC ${CAMERASUITE_LIBRARY})
endmacro()
